name: "ejabber-ami"

on:
  workflow_dispatch:
    
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  step1:
    name: "Build Ejabberd AMI"
    runs-on: "ubuntu-latest"
    defaults:
      run:
        shell: bash
        working-directory: .packer/ejabberd
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use latest Packer
        uses: hashicorp-contrib/setup-packer@v1

      - name: Build AMI
        run: packer build ejabberd.pkr.hcl
